### ISSUE TITLE
Auto layout problem

### ISSUE THREAD

**Issue by hanssl** [jonkykong/VerticalSlider#10]
I am using Xcode 9.4 and I am getting: 

"file:///Users/shane/data/src/vssl/vssl_ios/VSSL/Base.lproj/Main.storyboard: error: IB Designables: Failed to render and update auto layout status for AdvancedEqViewController (GAS-CK-jHf): dlopen(VerticalSlider.framework, 1): no suitable image found.  Did find:
	VerticalSlider.framework: required code signature missing for 'VerticalSlider.framework'"

**Comment by jonkykong** [comment]
This is a project problem, not an issue with VerticalSlider.
