### ISSUE TITLE
Not compatible with Swift 4.2

### ISSUE THREAD

**Issue by hanssl** [jonkykong/VerticalSlider#11]
<img width="1649" alt="screen shot 2018-10-10 at 11 53 21 am" src="https://user-images.githubusercontent.com/649957/46755765-25b1ee00-cc83-11e8-9672-31e6b8b5f1cb.png">

**Comment by kingsofteng** [comment]
You can just change the UIControlEvents to UIControl.Event on your source code.
Otherwise, you can wait for @jonkykong to merge new PR regarding "Swift 4.2 support".

**Comment by jonkykong** [comment]
Use 2.0.0.
