### ISSUE TITLE
Wrong project type setup in github

### ISSUE THREAD

**Issue by gmogames** [jonkykong/VerticalSlider#4]
Hi There,

Just noticed this project is setup as a SHELL type and not a SWIFT type on github:
![image](https://user-images.githubusercontent.com/1765046/27527013-4f029294-59fe-11e7-9caa-415337707a66.png)

People searching on swift will probably not find this.

**Comment by jonkykong** [comment]
@gmogames this isn't a project setting, it's just the assumed type based on the code the project contains. VerticalSlider is a very small piece of code so most of this project is Cocoapods scripts.
