### ISSUE TITLE
sender.tag in IBAction

### ISSUE THREAD

**Issue by Benny-iPhone** [jonkykong/VerticalSlider#7]
when using multiple VerticalSlider and hooking them all to a single IBAction method, the attempt to identify the sender using tag or isEqual will fail.

The reason is that the sender is not the VerticalSlider instance but the internal UISlider, please fix it.

**Comment by jonkykong** [comment]
Unfortunately I am not investing additional time to support this issue. Feel free to fix it yourself and submit a pull request to update this repository.
